export const galleryData = [
  { src: '/assets/img/img_1.jpg', alt: 'Работа 1', caption: 'Описание 1', author: 'Автор 1' },
  { src: '/assets/img/img_2.jpg', alt: 'Работа 2', caption: 'Описание 2', author: 'Автор 2' },
  { src: '/assets/img/img_3.jpg', alt: 'Работа 3', caption: 'Описание 3', author: 'Автор 3' },
  { src: '/assets/img/img_4.jpg', alt: 'Работа 4', caption: 'Описание 4', author: 'Автор 4' },
  { src: '/assets/img/img_5.jpg', alt: 'Работа 5', caption: 'Описание 5', author: 'Автор 5' },
  { src: '/assets/img/img_6.jpg', alt: 'Работа 6', caption: 'Описание 6', author: 'Автор 6' },
  { src: '/assets/img/img_7.jpg', alt: 'Работа 7', caption: 'Описание 7', author: 'Автор 7' },
  { src: '/assets/img/img_8.jpg', alt: 'Работа 8', caption: 'Описание 8', author: 'Автор 8' },
  { src: '/assets/img/img_9.jpg', alt: 'Работа 9', caption: 'Описание 9', author: 'Автор 9' },
  { src: '/assets/img/img_10.jpg', alt: 'Работа 10', caption: 'Описание 10', author: 'Автор 10' },
  { src: '/assets/img/img_11.jpg', alt: 'Работа 11', caption: 'Описание 11', author: 'Автор 11' },
  { src: '/assets/img/img_12.jpg', alt: 'Работа 12', caption: 'Описание 12', author: 'Автор 12' },
  { src: '/assets/img/img_13.jpg', alt: 'Работа 13', caption: 'Описание 13', author: 'Автор 13' },
  { src: '/assets/img/img_14.jpg', alt: 'Работа 14', caption: 'Описание 14', author: 'Автор 14' },
  { src: '/assets/img/img_15.jpg', alt: 'Работа 15', caption: 'Описание 15', author: 'Автор 15' },
];