# Generated by Django 5.1.4 on 2026-02-09 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "category",
                    models.CharField(
                        choices=[("children", "Дети"), ("adults", "Взрослые")],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("drawing", "Рисование"),
                            ("ceramics", "Керамика"),
                            ("creative_workshop", "Творческая мастерская"),
                            ("combo", "Комбо-занятия"),
                            ("prep_school", "Подготовка в художественную школу"),
                            ("individual", "Индивидуальные занятия"),
                            ("online", "Онлайн-уроки"),
                            ("masterclasses", "Мастер-классы"),
                            ("plein_air", "Пленэры"),
                            ("art_camp", "Арт-лагерь"),
                            ("special_events", "Специальные мероприятия"),
                            ("art_boxes", "Арт-боксы"),
                            ("gift_certificates", "Подарочные сертификаты"),
                            ("art_parties", "Арт-вечеринки"),
                        ],
                        max_length=50,
                    ),
                ),
                ("max_capacity", models.PositiveIntegerField(default=10)),
                (
                    "price",
                    models.DecimalField(decimal_places=0, default=0, max_digits=8),
                ),
                ("description", models.TextField(blank=True)),
                ("age_min", models.PositiveIntegerField(blank=True, default=0)),
                ("age_max", models.PositiveIntegerField(blank=True, default=99)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="reservations.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField()),
                ("teacher", models.CharField(blank=True, max_length=100)),
                ("is_fully_booked", models.BooleanField(default=False)),
                ("available_spots", models.PositiveIntegerField(default=10)),
                ("age_group", models.CharField(blank=True, max_length=50)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="reservations.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(blank=True, max_length=100)),
                ("user_surname", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("child_name", models.CharField(blank=True, max_length=100)),
                ("child_birthdate", models.DateField(blank=True, null=True)),
                (
                    "direction_manual",
                    models.CharField(
                        blank=True, help_text="Для броней без слота", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("art_box_type", models.CharField(blank=True, max_length=50)),
                ("delivery_type", models.CharField(blank=True, max_length=20)),
                ("certificate_type", models.CharField(blank=True, max_length=50)),
                (
                    "certificate_amount",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=8, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="reservations.timeslot",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "slot")},
            },
        ),
    ]
