# Generated by Django 5.1.4 on 2026-02-09 13:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Резервация', 'verbose_name_plural': 'Резервации'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ['start_time'], 'verbose_name': 'Временной слот', 'verbose_name_plural': 'Временные слоты'},
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='date_time',
        ),
        migrations.AddField(
            model_name='course',
            name='daily_capacity',
            field=models.PositiveIntegerField(default=8, help_text='Общее количество студентов в день для этого курса', verbose_name='Макс. человек в день'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 9, 13, 10, 38, 152420, tzinfo=datetime.timezone.utc), verbose_name='Начало'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='age_max',
            field=models.PositiveIntegerField(blank=True, default=99, verbose_name='Возраст до'),
        ),
        migrations.AlterField(
            model_name='course',
            name='age_min',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Возраст от'),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('children', 'Дети'), ('adults', 'Взрослые')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='course',
            name='direction',
            field=models.CharField(choices=[('drawing', 'Рисование'), ('ceramics', 'Керамика'), ('creative_workshop', 'Творческая мастерская'), ('combo', 'Комбо-занятия'), ('prep_school', 'Подготовка в художественную школу'), ('individual', 'Индивидуальные занятия'), ('online', 'Онлайн-уроки'), ('masterclasses', 'Мастер-классы'), ('plein_air', 'Пленэры'), ('art_camp', 'Арт-лагерь'), ('special_events', 'Специальные мероприятия'), ('art_boxes', 'Арт-боксы'), ('gift_certificates', 'Подарочные сертификаты'), ('art_parties', 'Арт-вечеринки')], max_length=50, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='reservations.location', verbose_name='Локация'),
        ),
        migrations.AlterField(
            model_name='course',
            name='max_capacity',
            field=models.PositiveIntegerField(default=10, verbose_name='Макс. человек в слоте'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=8, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='art_box_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип арт-бокса'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='certificate_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='Сумма сертификата'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='certificate_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип сертификата'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='child_birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения ребёнка'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя ребёнка'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='delivery_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Тип доставки'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='direction_manual',
            field=models.CharField(blank=True, help_text='Название курса для броней без слота', max_length=150, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='message',
            field=models.TextField(blank=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.timeslot', verbose_name='Временной слот'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает подтверждения'), ('confirmed', 'Подтверждена'), ('canceled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user_surname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='available_spots',
            field=models.PositiveIntegerField(default=10, verbose_name='Доступно мест'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='reservations.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='is_fully_booked',
            field=models.BooleanField(default=False, verbose_name='Полностью забронирован'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='teacher',
            field=models.CharField(blank=True, max_length=100, verbose_name='Преподаватель'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['course', 'start_time'], name='reservation_course__00e31d_idx'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['is_fully_booked'], name='reservation_is_full_67bf98_idx'),
        ),
    ]
